const EVENT_TYPES = {
  USER_FAILS_TO_EXECUTE_COMMAND: 'USER_FAILS_TO_EXECUTE_COMMAND',
  USER_EXECUTES_COMMAND: 'USER_EXECUTES_COMMAND',
  USER_SENDS_CALLBACK_QUERY: 'USER_SENDS_CALLBACK_QUERY',
  INCOMING_MESSAGE: 'INCOMING_MESSAGE',
};

module.exports = {
  EVENT_TYPES,
};
