- name: setup PostgreSQL DBMS
  block:
    - name: grant management user permissions
      become: true
      community.postgresql.postgresql_pg_hba:
        dest: /etc/postgresql/14/main/pg_hba.conf
        contype: host
        users: "{{ ansible_user }}"
        method: peer

    - name: create database
      community.postgresql.postgresql_db:
        name: "{{ DB_NAME }}"

    - name: create user
      community.postgresql.postgresql_user:
        name: "{{ DB_USER }}"
        password: "{{ DB_PASSWORD }}"
        encrypted: true

    - name: grant privileges
      community.postgresql.postgresql_privs:
        database: "{{ DB_NAME }}"
        type: database
        roles: "{{ DB_USER }}"
        privs: ALL
        state: present
