- name: setup PostgreSQL DBMS
  become: true
  become_user: postgres
  block:
    - name: create database
      community.postgresql.postgresql_db:
        name: "{{ DB_NAME }}"

    - name: create user
      community.postgresql.postgresql_user:
        name: "{{ DB_USER }}"
        password: "{{ DB_PASSWORD }}"
        encrypted: true

    - name: grant privileges
      community.postgresql.postgresql_privs:
        database: "{{ DB_NAME }}"
        type: database
        roles: "{{ DB_USER }}"
        privs: ALL
        state: present
