- name: update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: install packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - postgresql
      - python3-pip
    state: present

- name: install psycopg2
  ansible.builtin.pip:
    name: psycopg2-binary

- name: reboot
  ansible.builtin.reboot:
    reboot_timeout: 360
