- name: update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: download Nodesource repo setup script
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/setup_22.x
    dest: /tmp/nodesource_setup.sh

- name: add Nodesource repo
  become: true
  become_user: "root"
  ansible.builtin.command:
    chdir: "/tmp"
    cmd: "bash nodesource_setup.sh"

- name: install packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - postgresql
      - python3-pip
      - nodejs
    state: present

- name: install psycopg2
  ansible.builtin.pip:
    name: psycopg2-binary

- name: reboot
  ansible.builtin.reboot:
    reboot_timeout: 720
