- name: create db dump
  become: true
  become_user: "{{ OS_USER }}"
  environment:
    VELACH_BOT_DB_DATABASE: "{{ DB_NAME }}"
    VELACH_BOT_DB_USER: "{{ DB_USER }}"
    VELACH_BOT_DB_PASSWORD: "{{ DB_PASSWORD }}"
  ansible.builtin.command:
    chdir: "{{ REMOTE_SERVER_DIR }}"
    cmd: "npm run start:prod:cli -- --backup-db {{ DB_DUMP_DIR }} {{ DB_DUMP_FILENAME }}"
