# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "master", primary: true do |master|
    master.vm.box = "ubuntu/jammy64"
    master.vm.hostname = "velach-bot-master"

    master.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "512"
    end

    master.vm.network "private_network", ip: "192.168.26.5"

    master.vm.synced_folder "./.vagrant_data", "/vagrant_data"
    master.vm.synced_folder "./.ansible", "/home/vagrant/velach_bot_ansible"

    master.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y ansible dos2unix whois
      echo "export VELACH_BOT_OS_USER=\"velach_bot\"" >> /home/vagrant/.profile
      echo "export VELACH_BOT_OS_PASSWORD=\"!\"" >> /home/vagrant/.profile
      echo "export VELACH_BOT_OS_GROUP=\"velach_bot\"" >> /home/vagrant/.profile
      echo "export VELACH_BOT_DB_NAME=\"velach_bot\"" >> /home/vagrant/.profile
      echo "export VELACH_BOT_DB_USER=\"velach_bot\"" >> /home/vagrant/.profile
      echo "export VELACH_BOT_DB_PASSWORD=\"pass\"" >> /home/vagrant/.profile
      echo "export VELACH_BOT_DB_DUMP_DIR=\"/tmp\"" >> /home/vagrant/.profile
      echo "export VELACH_BOT_DB_DUMP_LINK=\"http://127.0.0.1/db_dump.sql\"" >> /home/vagrant/.profile
      echo "export VELACH_BOT_DB_DUMP_FILENAME=\"velach_bot_db_dump.sql\"" >> /home/vagrant/.profile
      echo "export VELACH_BOT_TELEGRAM_TOKEN=\"token\"" >> /home/vagrant/.profile
      echo "export VELACH_BOT_SERVER_DIST_DIR=\"/vagrant_data/dist\"" >> /home/vagrant/.profile
      echo "export VELACH_BOT_SERVER_DIR=\"/opt/velach_bot\"" >> /home/vagrant/.profile
      echo "export VELACH_BOT_SERVER_PACKAGE_JSON=\"/vagrant_data/package.json\"" >> /home/vagrant/.profile
      echo "export VELACH_BOT_SERVER_PACKAGE_LOCK_JSON=\"/vagrant_data/package-lock.json\"" >> /home/vagrant/.profile
    SHELL

    master.vm.provision "file", source: ".vagrant_keys/master", destination: "/home/vagrant/.ssh/id_rsa"
    master.vm.provision "file", source: ".vagrant_keys/master.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"

    master.vm.provision "shell", inline: <<-SHELL
      chmod 700 /home/vagrant/.ssh

      chmod 600 /home/vagrant/.ssh/id_rsa
      dos2unix /home/vagrant/.ssh/id_rsa

      chmod 644 /home/vagrant/.ssh/id_rsa.pub
      dos2unix /home/vagrant/.ssh/id_rsa.pub

      ssh-keyscan 192.168.26.6 >> /home/vagrant/.ssh/known_hosts
      chown vagrant /home/vagrant/.ssh/known_hosts
      chmod 600 /home/vagrant/.ssh/known_hosts
    SHELL


  end

  config.vm.define "slave" do |slave|
    slave.vm.box = "ubuntu/jammy64"
    slave.vm.hostname = "velach-bot-slave"

    slave.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "1024"
    end

    slave.vm.network "private_network", ip: "192.168.26.6"
    slave.vm.network "forwarded_port", guest: 5432, host: 65432

    slave.vm.synced_folder "./.vagrant_data", "/vagrant_data"

    slave.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y dos2unix
    SHELL

    slave.vm.provision "file", source: ".vagrant_keys/slave", destination: "/home/vagrant/.ssh/id_rsa"
    slave.vm.provision "file", source: ".vagrant_keys/slave.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"

    slave.vm.provision "shell" do |s|
      master_ssh_pub_key = File.readlines(".vagrant_keys/master.pub").first.strip
      s.inline = <<-SHELL
        echo #{master_ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{master_ssh_pub_key} >> /root/.ssh/authorized_keys
      SHELL
    end

    slave.vm.provision "shell", inline: <<-SHELL
      chmod 700 /home/vagrant/.ssh

      chmod 600 /home/vagrant/.ssh/id_rsa
      dos2unix /home/vagrant/.ssh/id_rsa

      chmod 644 /home/vagrant/.ssh/id_rsa.pub
      dos2unix /home/vagrant/.ssh/id_rsa.pub

      chmod 600 /home/vagrant/.ssh/authorized_keys
    SHELL
  end
end
