- name: Velach Bot Database Backup
  hosts: all
  vars:
    DUMP_TIMESTAMP: "{{ lookup('pipe', 'date +%d.%m.%Y-%H:%M:%S') }}"
  tasks:
    - name: Stop server application
      ansible.builtin.systemd:
        name: velach_bot_server.service
        state: stopped

    - name: Backup DB
      become: true
      become_user: "{{ OS_USER }}"
      environment:
        VELACH_BOT_DB_DATABASE: "{{ DB_NAME }}"
        VELACH_BOT_DB_USER: "{{ DB_USER }}"
        VELACH_BOT_DB_PASSWORD: "{{ DB_PASSWORD }}"
      ansible.builtin.command:
        chdir: "{{ APP_DIR }}"
        cmd: "./cli --backup-db velach_bot_database_dump_{{ DUMP_TIMESTAMP }}"

    - name: Start server application
      ansible.builtin.systemd:
        name: velach_bot_server.service
        state: started
