- name: velach_bot server provision
  hosts: all
  tasks:
    - name: include install_basic_software_role
      include_role:
        name: install_basic_software

    - name: include setup_os_user
      include_role:
        name: setup_os_user

    - name: include setup_postgres
      include_role:
        name: setup_postgres

    - name: include place_executables
      include_role:
        name: place_executables

    - name: include setup_blank_db
      include_role:
        name: setup_blank_db

    - name: include setup_systemd_units
      include_role:
        name: setup_systemd_units
