- name: Velach Bot Server Restart
  hosts: application-access
  tasks:
    - name: Restart server application
      ansible.builtin.command:
        chdir: "{{ APP_DIR }}"
        cmd: pm2 restart server
