- name: start server
  hosts: all
  tasks:
    - name: start server
      block:
        - name: include start_server
          include_role:
            name: start_server

        - name: include start_db_backup_timer
          include_role:
            name: start_db_backup_timer

        - name: include start_cleanup_dump_directory_timer
          include_role:
            name: start_cleanup_dump_directory_timer
