- name: server update
  hosts: all
  vars:
    OS_USER: "{{ lookup('ansible.builtin.env', 'VELACH_BOT_OS_USER') }}"
    OS_PASSWORD: "{{ lookup('ansible.builtin.env', 'VELACH_BOT_OS_PASSWORD') }}"
    OS_GROUP: "{{ lookup('ansible.builtin.env', 'VELACH_BOT_OS_GROUP') }}"
    DB_NAME: "{{ lookup('ansible.builtin.env', 'VELACH_BOT_DB_NAME') }}"
    DB_USER: "{{ lookup('ansible.builtin.env', 'VELACH_BOT_DB_USER') }}"
    DB_PASSWORD: "{{ lookup('ansible.builtin.env', 'VELACH_BOT_DB_PASSWORD') }}"
    DB_DUMP_DIR: "{{ lookup('ansible.builtin.env', 'VELACH_BOT_DB_DUMP_DIR') }}"
    DB_DUMP_FILENAME: "{{ lookup('ansible.builtin.env', 'VELACH_BOT_DB_DUMP_FILENAME') }}"
    TELEGRAM_TOKEN: "{{ lookup('ansible.builtin.env', 'VELACH_BOT_TELEGRAM_TOKEN') }}"
    SERVER_DIR: "{{ lookup('ansible.builtin.env', 'VELACH_BOT_SERVER_DIR') }}"
    DIST_ARCHIVE: "{{ lookup('ansible.builtin.env', 'VELACH_BOT_DIST_ARCHIVE') }}"
    REMOTE_ARCHIVE_PATH: "{{ lookup('ansible.builtin.env', 'VELACH_BOT_REMOTE_ARCHIVE_PATH') }}"
    JWT_SECRET: "{{ lookup('ansible.builtin.env', 'VELACH_BOT_JWT_SECRET') }}"
  tasks:
    - name: stop bot
      block:
        - name: include stop_server
          include_role:
            name: stop_server

        - name: include stop_db_backup_timer
          include_role:
            name: stop_db_backup_timer

        - name: include stop_db_backup_service
          ansible.builtin.systemd:
            name: stop_db_backup_service

        - name: include stop_cleanup_dump_directory_timer
          ansible.builtin.systemd:
            name: stop_cleanup_dump_directory_timer

        - name: include stop_cleanup_dump_directory_service
          ansible.builtin.systemd:
            name: stop_cleanup_dump_directory_service

    - name: include update_server_files
      include_role:
        name: update_server_files

    - name: include create_db_dump
      include_role:
        name: create_db_dump

    - name: include apply_db_migrations
      include_role:
        name: apply_db_migrations

    - name: include setup_systemd_units
      include_role:
        name: setup_systemd_units

    - name: start bot
      block:
        - name: include start_server
          include_role:
            name: start_server

        - name: include start_db_backup_timer
          include_role:
            name: start_db_backup_timer

        - name: include start_cleanup_dump_directory_timer
          include_role:
            name: start_cleanup_dump_directory_timer
