export const FEATURE_KEYS = {
  ['bikecheck-command/callback-query/delete']: 1,
  ['bikecheck-command/callback-query/delete-strava']: 2,
  ['bikecheck-command/callback-query/toggle-on-sale']: 3,
  ['bikecheck-command/callback-query/like']: 4,
  ['bikecheck-command/callback-query/dislike']: 5,
  ['bikecheck-command/callback-query/show-next-bikecheck']: 6,
  ['bikecheck-command/callback-query/show-previous-bikecheck']: 7,
  ['bikecheck-command/inline-command']: 8,
  ['bikecheck-command/message-command']: 9,
  ['checkbike-command']: 10,
  ['mylikes-command/message-command']: 11,
  ['mylikes-command/callback-query/show-previous']: 12,
  ['mylikes-command/callback-query/show-next']: 13,
  ['deleted-command/callback-query/restore']: 14,
  ['deleted-command/callback-query/show-next']: 15,
  ['deleted-command/callback-query/show-previous']: 16,
  ['deleted-command/message-command']: 17,
  ['help-command']: 18,
  ['onsale-command/callback-query/show-previous']: 19,
  ['onsale-command/callback-query/show-next']: 20,
  ['onsale command/message-command']: 21,
  ['setstrava-command/message-command']: 22,
  ['start-command/message-command']: 23,
  ['top-command/callback-query/show-top']: 24,
  ['top-command/message-command']: 25,
} as const;
