- name: apply db migrations
  environment:
    VELACH_BOT_DB_DATABASE: "{{ DB_NAME }}"
    VELACH_BOT_DB_USER: "{{ DB_USER }}"
    VELACH_BOT_DB_PASSWORD: "{{ DB_PASSWORD }}"
  ansible.builtin.command:
    chdir: "{{ REMOTE_SERVER_DIR }}"
    cmd: "npm run start:prod:cli -- --apply-migrations"
