- name: create bot directory
  ansible.builtin.file:
    path: "{{ APP_DIR }}"
    owner: "{{ OS_USER }}"
    group: "{{ OS_GROUP }}"
    state: directory
    recurse: true

- name: copy server executable
  ansible.builtin.copy:
    src: "{{ DIST_BINARY_DIR }}/main"
    dest: "{{ APP_DIR }}"
    owner: "{{ OS_USER }}"
    group: "{{ OS_GROUP }}"
    mode: "755"

- name: copy cli executable
  ansible.builtin.copy:
    src: "{{ DIST_BINARY_DIR }}/cli"
    dest: "{{ APP_DIR }}"
    owner: "{{ OS_USER }}"
    group: "{{ OS_GROUP }}"
    mode: "755"
