- name: copy archive
  ansible.builtin.copy:
    src: "{{ DIST_ARCHIVE }}"
    dest: "{{ REMOTE_ARCHIVE_PATH }}"
    owner: "{{ OS_USER }}"
    group: "{{ OS_GROUP }}"
    mode: "755"
    force: true

- name: extract archive
  ansible.builtin.unarchive:
    src: "{{ REMOTE_ARCHIVE_PATH }}"
    dest: "{{ SERVER_DIR }}"
    owner: "{{ OS_USER }}"
    group: "{{ OS_GROUP }}"
    mode: "755"
    remote_src: true

- name: install deps
  become: true
  become_user: "{{ OS_USER }}"
  community.general.npm:
    path: "{{ SERVER_DIR }}"
    ci: true

- name: delete archive
  ansible.builtin.file:
    path: "{{ REMOTE_ARCHIVE_PATH }}"
    state: absent
