- name: create dist archive
  community.general.archive:
    path:
      - "{{ SERVER_DIST_DIR }}"
      - "{{ SERVER_PACKAGE_JSON }}"
      - "{{ SERVER_PACKAGE_LOCK_JSON }}"
    dest: "{{ REMOTE_DIST_ARCHIVE }}"

- name: unpack dist archive
  ansible.builtin.unarchive:
    src: "{{ REMOTE_DIST_ARCHIVE }}"
    dest: "{{ SERVER_DIR }}"
    owner: "{{ OS_USER }}"
    group: "{{ OS_GROUP }}"
    mode: "755"
    remote_src: yes

- name: install deps
  become: true
  become_user: "{{ OS_USER }}"
  community.general.npm:
    path: "{{ SERVER_DIR }}"
    ci: true
