name: Clean Old Dumps
on:
  workflow_dispatch:
jobs:
  clean_old_dumps:
    name: Clean Old Dumps
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch Repo
        uses: actions/checkout@v3

      - name: Run Playbook
        env:
          VELACH_BOT_DB_DUMP_DIR: /tmp
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: server/.ansible/clean_old_dumps.yml
          inventory: |
            ${{ secrets.INVENTORY }}
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          options: |
            --inventory "server/.ansible/inventories/production.yml"
