name: Provision
on:
  workflow_dispatch:
jobs:
  provision:
    name: Provision
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch Repo
        uses: actions/checkout@v2

      - name: Install Node JS
        uses: actions/setup-node@v2
        with:
          node-version: 20.17.0
          cache: "npm"
          cache-dependency-path: server/package-lock.json

      - name: Setup PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "12"
          postgresql db: "velach_bot"
          postgresql user: "velach_bot"
          postgresql password: "pass"

      - name: Install Dependencies
        working-directory: server
        run: npm ci

      - name: Run Linter
        working-directory: server
        run: npm run lint

      - name: Create DB Tables
        working-directory: server
        run: npm run create-tables

      - name: Seed Test DB
        working-directory: server
        run: npm run seed-test-db

      - name: Run Tests
        working-directory: server
        run: npm run test

      - name: Build Javascript
        working-directory: server
        run: npm run build

      - name: Build Binaries
        working-directory: server
        run: |
          npm run build-binary:cli
          npm run build-binary:bot

      - name: Run Playbook
        env:
          VELACH_BOT_DIST_BINARY_DIR: ${{ github.workspace }}/server/dist-binary
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: server/.ansible/provision.yml
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          options: |
            --inventory "server/.ansible/inventories/production.yml"
