name: Server Provision
on:
  workflow_dispatch:
jobs:
  provision:
    name: Setup New Server
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch Repo
        uses: actions/checkout@v4

      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: "npm"
          cache-dependency-path: server/package-lock.json

      - name: Setup PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "14"
          postgresql db: "velach_bot"
          postgresql user: "velach_bot"
          postgresql password: "pass"

      - name: Install Dependencies
        working-directory: server
        run: npm ci

      - name: Run Linter
        working-directory: server
        run: npm run lint

      - name: Create DB Tables
        working-directory: server
        run: npm run create-tables

      - name: Seed Test DB
        working-directory: server
        run: npm run seed-test-db

      - name: Run Tests
        working-directory: server
        run: npm run test

      - name: Build Javascript
        working-directory: server
        run: npm run build

      - name: Run Playbook
        env:
          VELACH_BOT_OS_USER: ${{ secrets.OS_USER }}
          VELACH_BOT_OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          VELACH_BOT_OS_GROUP: ${{ secrets.OS_GROUP }}
          VELACH_BOT_DB_NAME: ${{ secrets.DB_NAME }}
          VELACH_BOT_DB_USER: ${{ secrets.DB_USER }}
          VELACH_BOT_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          VELACH_BOT_DB_DUMP_DIR: /home/${{ secrets.OS_USER }}/dumps
          VELACH_BOT_DB_DUMP_LINK: ${{ secrets.DB_DUMP_LINK }}
          VELACH_BOT_DB_DUMP_FILENAME: velach_bot_provision_dump.sql
          VELACH_BOT_TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          VELACH_BOT_REMOTE_SERVER_DIR: /opt/velach_bot
          VELACH_BOT_LOCAL_DIST_ARCHIVE: ${{ github.workspace }}/velach_bot_${{ github.sha }}.tar
          VELACH_BOT_REMOTE_DIST_ARCHIVE: /tmp/velach_bot_${{ github.sha }}.tar
          VELACH_BOT_JWT_SECRET: ${{ secrets.JWT_SECRET }}
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: server/.ansible/provision.yml
          inventory: |
            ${{ secrets.INVENTORY }}
