name: Release Workflow

on:
  push:
    branches: 
    - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 14.18.1 ]
    env:
      VELACH_BOT_DB_HOST: '127.0.0.1'
      VELACH_BOT_DB_PORT: '5432'
      VELACH_BOT_DB_DATABASE: 'velach_bot'
      VELACH_BOT_DB_USER: 'velach_bot'
      VELACH_BOT_DB_PASSWORD: 'pass'

    steps:
    - name: Fetch Repo
      uses: actions/checkout@v2

    - name: Setup PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '12'
        postgresql db: 'velach_bot'
        postgresql user: 'velach_bot'
        postgresql password: 'pass'

    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Local Dependencies
      run: npm ci

    - name: Create DB Tables
      run: npm run create-tables

    - name: Seed Test DB
      run: npm run seed-test-db

    - name: Run Tests
      run: npm run test

    - name: Build
      run: npm run build

    - name: Prepare Distribution Folder
      run: |
        mv package.json dist/package.json
        mv package-lock.json dist/package-lock.json
        mv src/common/database/migrations dist/common/database/migrations

    - name: Stop Bot
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_SERVER_HOST }}
        port: ${{ secrets.PROD_SERVER_PORT }}
        username: ${{ secrets.PROD_SERVER_USER }}
        key: ${{ secrets.COMMAND_EXECUTION_KEY }}
        script: pm2 stop "Velach Bot"

    - name: Backup Database
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_SERVER_HOST }}
        port: ${{ secrets.PROD_SERVER_PORT }}
        username: ${{ secrets.PROD_SERVER_USER }}
        key: ${{ secrets.COMMAND_EXECUTION_KEY }}
        script: |
          cd velach_bot
          export VELACH_BOT_DB_DATABASE="${{ secrets.DB_NAME }}"
          export VELACH_BOT_DB_HOST="${{ secrets.DB_HOST }}"
          export VELACH_BOT_DB_PORT="${{ secrets.DB_PORT }}"
          export VELACH_BOT_DB_USER="${{ secrets.DB_USER }}"
          export VELACH_BOT_DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          export VELACH_BOT_DROPBOX_TOKEN="${{ secrets.DROPBOX_ACCESS_TOKEN }}"
          node cli.js --backup-db pre-deploy-dump-${{ github.sha }}

    - name: Copy Distribution To Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.FILE_TRANSFER_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.PROD_SERVER_HOST }}
        REMOTE_PORT: ${{ secrets.PROD_SERVER_PORT }}
        REMOTE_USER: ${{ secrets.PROD_SERVER_USER }}
        TARGET: ${{ secrets.PROD_SERVER_APP_ROOT }}

    - name: Install Server Dependencies
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_SERVER_HOST }}
        port: ${{ secrets.PROD_SERVER_PORT }}
        username: ${{ secrets.PROD_SERVER_USER }}
        key: ${{ secrets.COMMAND_EXECUTION_KEY }}
        script: |
          cd velach_bot
          npm ci

    - name: Apply Migrations
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_SERVER_HOST }}
        port: ${{ secrets.PROD_SERVER_PORT }}
        username: ${{ secrets.PROD_SERVER_USER }}
        key: ${{ secrets.COMMAND_EXECUTION_KEY }}
        script: |
          cd velach_bot
          export VELACH_BOT_DB_DATABASE="${{ secrets.DB_NAME }}"
          export VELACH_BOT_DB_HOST="${{ secrets.DB_HOST }}"
          export VELACH_BOT_DB_PORT="${{ secrets.DB_PORT }}"
          export VELACH_BOT_DB_USER="${{ secrets.DB_USER }}"
          export VELACH_BOT_DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          node cli.js --apply-migrations

    - name: Restart Bot
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_SERVER_HOST }}
        port: ${{ secrets.PROD_SERVER_PORT }}
        username: ${{ secrets.PROD_SERVER_USER }}
        key: ${{ secrets.COMMAND_EXECUTION_KEY }}
        script: pm2 restart "Velach Bot"
