name: Release Workflow

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 14.18.1 ]
    env:
      VELACH_BOT_DB_HOST: '127.0.0.1'
      VELACH_BOT_DB_PORT: '5432'
      VELACH_BOT_DB_DATABASE: 'velach_bot'
      VELACH_BOT_DB_USER: 'velach_bot'
      VELACH_BOT_DB_PASSWORD: 'pass'
    steps:
    - name: Fetch Repo
      uses: actions/checkout@v2
    
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '12'
        postgresql db: 'velach_bot'
        postgresql user: 'velach_bot'
        postgresql password: 'pass'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Create DB Tables
      run: npm run create-tables
    
    - name: Seed Test DB
      run: npm run seed-test-db
    
    - name: Run Tests
      run: npm run test
  
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: run_tests
    strategy:
      matrix:
        node-version: [ 14.18.1 ]
    steps:
    - name: Fetch Repo
      uses: actions/checkout@v2
    
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
      
    - name: Prepare Distribution Folder
      run: |
        mv node_modules dist/node_modules
        mv src/common/database/migrations dist/common/database/migrations
        
    - name: Stop Bot
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_SERVER_HOST }}
        port: ${{ secrets.PROD_SERVER_PORT }}
        username: ${{ secrets.PROD_SERVER_USER }}
        key: ${{ secrets.COMMAND_EXECUTION_KEY }}
        script: pm2 stop ecosystem.config.js
        
    - name: Copy Distribution To Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.FILE_TRANSFER_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.PROD_SERVER_HOST }}
        REMOTE_PORT: ${{ secrets.PROD_SERVER_PORT }}
        REMOTE_USER: ${{ secrets.PROD_SERVER_USER }}
        TARGET: ${{ secrets.PROD_SERVER_APP_ROOT }}

    - name: Backup Database
      uses: appleboy/ssh-action@master
      env:
        VELACH_BOT_DB_DATABASE: ${{ secrets.DB_NAME }}
        VELACH_BOT_DB_HOST: ${{ secrets.DB_HOST }}
        VELACH_BOT_DB_PORT: ${{ secrets.DB_PORT }}
        VELACH_BOT_DB_USER: ${{ secrets.DB_USER }}
        VELACH_BOT_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        VELACH_BOT_DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
      with:
        host: ${{ secrets.PROD_SERVER_HOST }}
        port: ${{ secrets.PROD_SERVER_PORT }}
        username: ${{ secrets.PROD_SERVER_USER }}
        key: ${{ secrets.COMMAND_EXECUTION_KEY }}
        envs: VELACH_BOT_DB_DATABASE,VELACH_BOT_DB_HOST,VELACH_BOT_DB_PORT,VELACH_BOT_DB_USER,VELACH_BOT_DB_PASSWORD,VELACH_BOT_DROPBOX_ACCESS_TOKEN
        script: |
          cd velach_bot
          node cli.js --backup-db pre-deploy-dump
          
    - name: Apply Migrations
      uses: appleboy/ssh-action@master
      env:
        VELACH_BOT_DB_DATABASE: ${{ secrets.DB_NAME }}
        VELACH_BOT_DB_HOST: ${{ secrets.DB_HOST }}
        VELACH_BOT_DB_PORT: ${{ secrets.DB_PORT }}
        VELACH_BOT_DB_USER: ${{ secrets.DB_USER }}
        VELACH_BOT_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      with:
        host: ${{ secrets.PROD_SERVER_HOST }}
        port: ${{ secrets.PROD_SERVER_PORT }}
        username: ${{ secrets.PROD_SERVER_USER }}
        key: ${{ secrets.COMMAND_EXECUTION_KEY }}
        envs: VELACH_BOT_DB_DATABASE,VELACH_BOT_DB_HOST,VELACH_BOT_DB_PORT,VELACH_BOT_DB_USER,VELACH_BOT_DB_PASSWORD
        script: |
          cd velach_bot
          node cli.js --apply-migrations
    
    - name: Restart Bot
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_SERVER_HOST }}
        port: ${{ secrets.PROD_SERVER_PORT }}
        username: ${{ secrets.PROD_SERVER_USER }}
        key: ${{ secrets.COMMAND_EXECUTION_KEY }}
        script: pm2 restart ecosystem.config.js
