name: Restart Server
on:
  workflow_dispatch:
jobs:
  restart-server:
    name: Restart Server
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch Repo
        uses: actions/checkout@v3

      - name: Run Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: server/.ansible/restart_server.yml
          inventory: |
            ${{ secrets.PRODUCTION_INVENTORY }}
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          options: |
            --inventory "server/.ansible/inventories/production.yml"
