name: Server Tests
on:
  push:
    branches:
      - feature/**
      - fix/**
      - master
    paths:
      - server/**
      - .github/workflows/**
  workflow_dispatch:
jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch Repo
        uses: actions/checkout@v3

      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
          cache: npm
          cache-dependency-path: server/package-lock.json

      - name: Setup PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "12"
          postgresql db: "velach_bot"
          postgresql user: "velach_bot"
          postgresql password: "pass"

      - name: Install Dependencies
        working-directory: server
        run: npm ci

      - name: Create DB Tables
        working-directory: server
        run: npm run create-tables

      - name: Seed Test DB
        working-directory: server
        run: npm run seed-test-db

      - name: Run Tests
        working-directory: server
        run: npm run test

      - name: Run Linter
        working-directory: server
        run: npm run lint
