name: Server Tests Workflow

on:
  push:
    branches:
    - feature/**
    - fix/**
    - master
    paths:
    - server/**
    - .github/workflows/**
  workflow_dispatch:

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 14.18.1 ]
    env:
      VELACH_BOT_DB_HOST: '127.0.0.1'
      VELACH_BOT_DB_PORT: '5432'
      VELACH_BOT_DB_DATABASE: 'velach_bot'
      VELACH_BOT_DB_USER: 'velach_bot'
      VELACH_BOT_DB_PASSWORD: 'pass'

    steps:
    - name: Fetch Repo
      uses: actions/checkout@v2

    - name: Install Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json

    - name: Setup PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '12'
        postgresql db: 'velach_bot'
        postgresql user: 'velach_bot'
        postgresql password: 'pass'

    - name: Install Dependencies
      working-directory: server
      run: npm ci

    - name: Create DB Tables
      working-directory: server
      run: npm run create-tables

    - name: Seed Test DB
      working-directory: server
      run: npm run seed-test-db

    - name: Run Tests
      working-directory: server
      run: npm run test
