name: Start Server
on:
  workflow_dispatch:
jobs:
  start_server:
    name: Start server
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch Repo
        uses: actions/checkout@v3

      - name: Run Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: server/.ansible/start_server.yml
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          options: |
            --inventory "server/.ansible/inventories/production.yml"
