name: Start PM2 Ecosystem
on:
  workflow_dispatch:
jobs:
  server_provision:
    steps:
      - name: Run Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: server/.ansible/start-ecosystem.yml
          vault_password: ${{secrets.VAULT_PASSWORD}}
          options: |
            --inventory "server/.ansible/inventory.yml"
            --verbose
