name: Start Server
on:
  workflow_dispatch:
jobs:
  start_server:
    name: Start server
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch Repo
        uses: actions/checkout@v4

      - name: Run Playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: server/.ansible/start_server.yml
          inventory: |
            ${{ secrets.INVENTORY }}
