name: Stop Server
on:
  workflow_dispatch:
jobs:
  stop_server:
    name: Stop server
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch Repo
        uses: actions/checkout@v4

      - name: Run Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: server/.ansible/stop_server.yml
          inventory: |
            ${{ secrets.INVENTORY }}
