name: Stop Server
on:
  workflow_dispatch:
jobs:
  server_provision:
    name: Stop server
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch Repo
        uses: actions/checkout@v3

      - name: Run Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: server/.ansible/stop-server.yml
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          options: |
            --inventory "server/.ansible/inventory.yml"
